# Generated by Django 2.0.13 on 2019-04-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190323_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['branch_shortcut']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_safo_number',
            field=models.IntegerField(null=True),
        ),
    ]
