# Generated by Django 2.0.13 on 2019-05-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190417_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_svp_id',
            field=models.IntegerField(null=True),
        ),
    ]
