# Generated by Django 2.2.1 on 2019-05-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_auto_20190417_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_type_name', models.CharField(max_length=50)),
                ('overtime_hour_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_date_begin', models.DateTimeField()),
                ('overtime_date_end', models.DateTimeField()),
                ('overtime_user', models.CharField(max_length=50)),
                ('overtime_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Branch')),
                ('overtime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime.Overtime_type')),
            ],
            options={
                'ordering': ['overtime_date_begin'],
            },
        ),
    ]
