# Generated by Django 2.2.1 on 2019-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='overtime_user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
