# Generated by Django 2.0.13 on 2019-03-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190328_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.CharField(default='bugs', max_length=50),
        ),
    ]
